
trigger:
- '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build all'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 
        checkLatest: true

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: 'Build API project'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-r linux-x64 --output $(build.artifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish API'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'API_drop'
        publishLocation: 'Container'

    - task: DeleteFiles@1
      displayName: 'Delete API build artifact files'
      inputs:
        SourceFolder: '$(build.artifactStagingDirectory)'
        Contents: '**'

    - task: VSBuild@1
      displayName: 'Build SQL DB project'
      inputs:
        solution: 'Database/TaskFocusData/TaskFocusData.sqlproj'
        msbuildArgs: '/p:OutDir="$(build.artifactStagingDirectory)" /property:DSP="Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish SQL Database'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'SQLdb_drop'
        publishLocation: 'Container'

    - task: DeleteFiles@1
      displayName: 'Delete SQL DB build artifact files'
      inputs:
        SourceFolder: '$(build.artifactStagingDirectory)'
        Contents: '**'

    - task: DotNetCoreCLI@2
      displayName: 'Build DesktopUI project'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'DesktopUI/TaskFocusDesktop/TaskFocusDesktop.csproj'
        arguments: '-p:PublishSingleFile=true --runtime win-x64 --self-contained true --output $(build.artifactStagingDirectory)'
        zipAfterPublish: false

    - task: PublishBuildArtifacts@1
      displayName: 'Publish DesktopUI'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'DesktopUI_drop'
        publishLocation: 'Container'

    - task: DeleteFiles@1
      displayName: 'Delete DesktopUI build artifact files'
      inputs:
        SourceFolder: '$(build.artifactStagingDirectory)'
        Contents: '**'
        
    - task: CmdLine@2
      displayName: 'Build EF ApiAuth DB'
      inputs:
        script: |
          dotnet tool install --global dotnet-ef
          dotnet ef migrations script -i -o $(build.artifactStagingDirectory)\migrate.sql -p API\TaskFocusAPI\TaskFocusAPI.csproj

    - task: PublishBuildArtifacts@1
      displayName: 'Publish EF ApiAuth DB'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'AuthDB_drop'
        publishLocation: 'Container'
  
- stage: 'Dev'
  displayName: 'Deploy to the dev environment'
  dependsOn: Build
  condition:  succeeded()
  jobs:
  - deployment: Deploy_Linux
    displayName: 'Deploy (Linux) job'
    pool:
      vmImage: 'ubuntu-20.04'
    environment: dev
    strategy:
      runOnce:
        deploy:

          steps:
          - download: current
            displayName: 'Download API artifact'
            artifact: API_drop

          - task: AzureWebApp@1
            displayName: 'Deploy API'
            inputs:
              azureSubscription: 'Azure subscription 1(0af9f1a9-e361-440d-926a-b29173434193)'
              appType: 'webAppLinux'
              appName: 'TaskFocusAPI'
              package: '$(Pipeline.Workspace)/API_drop/TaskFocusAPI.zip'

  - deployment: Deploy_Win
    displayName: 'Deploy (Windows) job'
    pool:
      vmImage: 'windows-latest'
    environment: dev
    strategy:
      runOnce:
        deploy:

          steps:
          - task: SqlAzureDacpacDeployment@1
            displayName: 'Deploy AuthDB'
            inputs:
              azureSubscription: 'Azure subscription 1(0af9f1a9-e361-440d-926a-b29173434193)'
              AuthenticationType: 'server'
              ServerName: '$(SQLServer)'
              DatabaseName: '$(AuthDBName)'
              SqlUsername: '$(SQLUserName)'
              SqlPassword: '$(SQLPassword)'
              deployType: 'SqlTask'
              SqlFile: '$(Pipeline.Workspace)/AuthDB_drop/migrate.sql'
              IpDetectionMethod: 'AutoDetect'

          - task: SqlAzureDacpacDeployment@1
            displayName: 'Deploy DataDB'
            inputs:
              azureSubscription: 'Azure subscription 1(0af9f1a9-e361-440d-926a-b29173434193)'
              AuthenticationType: 'server'
              ServerName: '$(SQLServer)'
              DatabaseName: '$(DataDBName)'
              SqlUsername: '$(SQLUserName)'
              SqlPassword: '$(SQLPassword)'
              deployType: 'DacpacTask'
              DeploymentAction: 'Publish'
              DacpacFile: '$(Pipeline.Workspace)/SQLdb_drop/TaskFocusData.dacpac'
              IpDetectionMethod: 'AutoDetect'

          - task: AzureFileCopy@5
            displayName: 'AzureBlob DesktopUI exe File Copy'
            inputs:
              SourcePath: '$(Pipeline.Workspace)/DesktopUI_drop/TaskFocusDesktop/TaskFocusDesktop.exe'
              azureSubscription: 'Azure subscription 1(0af9f1a9-e361-440d-926a-b29173434193)'
              Destination: 'AzureBlob'
              storage: 'taskfocusblobstorage'
              ContainerName: 'applications'