CREATE TABLE [dbo].[Context]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [UserId] NVARCHAR(128) NOT NULL, 
    [ContextName] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [FK_Context_ToUser] FOREIGN KEY (UserId) REFERENCES [User](Id)
)
